import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Toaster } from "./_components/ui/sonner"
import Footer from "./_components/layout/footer"
import NextAuthProvider from "./_providers/auth"
import { AuthProvider } from "./_lib/auth-provider"

// Configuração da fonte Inter do Google Fonts
const inter = Inter({ subsets: ["latin"] })

// Metadados para o documento
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

// Componente RootLayout que envolve a aplicação
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <AuthProvider>
          <NextAuthProvider>
            <div className="flex min-h-screen flex-col">
              <div className="flex-1">{children}</div>
              <Footer />
            </div>
          </NextAuthProvider>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  )
}
